### ISSUE TITLE
SendGrid v3 and HTML emails - Creates bad Json

### ISSUE THREAD

**Issue by Surfrat** [sendgrid/sendgrid-csharp#256]
I used the v2 API with no problems. I am now using the v3 API and I get a BadRequest response after sending. I investigated with Fiddler and I can see that the Json that is created for my email is bad.

See [my problem here](https://community.sendgrid.com/sendgrid/topics/sendgrid-v3-and-html-emails-creates-bad-json).

Thanks

Mark.

**Comment by gliljas** [comment]
The issue is in CSharpHttpClient/Client.cs which for no valid reason does this:

`if (requestBody != null)
                    {
                        content = new StringContent(requestBody.ToString().Replace("'", "\""), Encoding.UTF8, MediaType);
                    }`

**Comment by thinkingserious** [comment]
Thanks @gliljas!

That feedback should speed the resolution of this issue.

**Comment by cosaques** [comment]
I had the same problem

**Comment by georgeemr** [comment]
same problem!!!

**Comment by thinkingserious** [comment]
Hello @gliljas, @cosaques and @georgeemr,

I believe this is fixed in v7.0.3.

**Comment by gliljas** [comment]
It solves the problem, but I strongly disagree with the solution. CSharpHttpClient still replaces single quotes with double quotes, which is has no business doing. If someone wants to use CSharpHttpClient as a generic API client, they will be surprised to find that it modifies the valid JSON.

Trust JSON.NET to do the right thing without any special escaping settings. It always produces valid JSON, such as 

`{"sender" : "McDonald's"}`

**Comment by thinkingserious** [comment]
@gliljas,

I recall having some issues with the JSON.NET results, that is why I implemented that hack. I believe it had something to do with this: http://stackoverflow.com/a/10679340 but I'm not sure.

I know that is not the best answer and I'll leave this ticket open so we further investigate come up with a better solution.

If you have any suggestions, please let me know.

Thank you very much for your support and for taking the time to suggest improvements!

**Comment by gliljas** [comment]
I opened this issue: https://github.com/sendgrid/csharp-http-client/issues/7

...since that's where the problem is.

**Comment by georgeemr** [comment]
I'm still getting the BadRequest with the last version. With Advanced Rest Client response is OK and email is sending good.

![rest](https://cloud.githubusercontent.com/assets/3822009/16435460/67a24132-3d53-11e6-8e36-cb9409e8acb8.jpg)

I'm attaching the mail.Get() result:

`"subject": "Su solicitud de crédito",
	"personalizations": [{
		"to": [{
			"email": "jorge@vehiventa.com"
		}]
	}],
	"content": [{
		"type": "text/plain",
		"value": "\r\n\r\nHola Adri\u0026#225;n Navarro!\r\nSu solicitud de Compra de lote ha sido creada.\r\n    Monto: ₡20,000,000.00\r\n    \r\n    Antes de que un ejecutivo acepte su solicitud, usted tiene la oportunidad de poder cancelarla en cualquier momento desde el menú de solicitudes.\r\n    \r\n    Los productos que usted solicitó son los siguientes:\r\n    \r\n            \r\n                Cr\u0026#233;dito hipotecario. - Lafise\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 30 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.16%\r\n                    Cuota aproximada: ₡132,389.58\r\n                        Seguros: por definir\r\n                        Porcentaje de la comisión: 3.00%\r\n                        Comisión: ₡600,000.00\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa fija6.95%Del mes 1 hasta mes 24                        Tasa Libor 3 Meses + 8.00% o Piso de 8.25%8.66655%Del mes 25 hasta mes 360                                                                                            \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 27/05/2016\r\n                    Fuente: Sucursal de Pavas \r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n            \r\n                Cr\u0026#233;dito hipotecario - tasa variable. - Scotiabank\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario - tasa variable.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 25 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.06%\r\n                    Cuota aproximada: ₡131,933.88\r\n                        Seguros: por definir\r\n                        Porcentaje de la comisión: 1.00%\r\n                        Comisión: ₡200,000.00\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa NY Prime + 2.75%6.25%Del mes 1 hasta mes 12                        Tasa NY Prime + 3.40%6.90%Del mes 13 hasta mes 36                        Tasa NY Prime + 4.75%8.25%Del mes 37 hasta mes 300                                                                    \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 16/06/2016\r\n                    Fuente: Expo Construcci\u0026#243;n.\r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n            \r\n                Cr\u0026#233;dito hipotecario. - BAC San Jos\u0026#233;\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 30 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.35%\r\n                    Cuota aproximada: ₡135,305.06\r\n                        Seguros: por definir\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa Libor 3 Meses + 6.50% o Piso de 7.00%7.16655%Del mes 1 hasta mes 36                        Tasa Libor 3 Meses + 7.90% o Piso de 8.50%8.56655%Del mes 37 hasta mes 360                                                                                            \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 21/06/2016\r\n                    Fuente: BAC San Jos\u0026#233;, - https://server.iad.liveperson.net/hc/49782067/?visitor=\u0026amp;msessionkey=\u0026amp;cmd=file\u0026amp;file=visitorWantsToChat\u0026amp;site=49782067\u0026amp;channel=web\u0026amp;d=1242\r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n            \r\n                Cr\u0026#233;dito hipotecario - tasa fija escalonada. - Banca Kristal\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario - tasa fija escalonada.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 30 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.40%\r\n                    Cuota aproximada: ₡126,413.60\r\n                        Seguros: por definir\r\n                        Porcentaje de la comisión: 2.00%\r\n                        Comisión: ₡400,000.00\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa NY Prime + 3.00%6.50%Del mes 1 hasta mes 12                        Tasa NY Prime + 4.00%7.50%Del mes 13 hasta mes 24                        Tasa NY Prime + 5.00%8.50%Del mes 25 hasta mes 360                                                                    \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 24/05/2016\r\n                    Fuente: Recopilaci\u0026#243;n de datos v\u0026#237;a correo electr\u0026#243;nico.\r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n    \r\n    \r\n            Tasa b\u0026#225;sica pasiva al 28/06/2016: 5.3%\r\n            Tasa NY Prime al 28/06/2016: 3.5%\r\n            Tasa Libor 1 Mes al 28/06/2016: 0.4508%\r\n            Tasa Libor 3 Meses al 28/06/2016: 0.64185%\r\n            Tasa Libor 6 Meses al 28/06/2016: 0.93115%\r\n            Tasa Libor 12 Meses al 28/06/2016: 1.2525%\r\n    \r\n    \r\n    \r\n        Tambi\u0026#233;n, usted aceptó recibir ofertas de otras entidades.\r\n        Si una entidad decide ofertarle le estaremos enviando un correo para notificarle.\r\n    \r\n    Usted puede aceptar o rechazar las ofertas recibidas de otras entidades que usted no escogió en esta solicitud.\r\n    Puede dejar de recibir ofertas cancelando la solicitud desde el menú de Oferentes.\r\nEste correo ha sido generado automáticamente, por favor no responder."
	}, {
		"type": "text/html",
		"value": "\r\n\r\n\u003ch3 style=\u0022color:#650B5F\u0022\u003eHola Adri\u0026#225;n Navarro!\u003c/h3\u003e\r\n\u003cp style=\u0022color:#650B5F\u0022\u003eSu solicitud de Compra de lote ha sido creada.\u003c/p\u003e\r\n    \u003cp\u003eMonto: ₡20,000,000.00\u003c/p\u003e\r\n    \u003chr /\u003e\r\n    \u003cp\u003eAntes de que un ejecutivo acepte su solicitud, usted tiene la oportunidad de poder cancelarla en cualquier momento desde el menú de solicitudes.\u003c/p\u003e\r\n    \u003cbr /\u003e\r\n    \u003cstrong\u003eLos productos que usted solicitó son los siguientes:\u003c/strong\u003e\r\n    \u003cdiv\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario. - Lafise\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario.\u0022 src=\u0022https://bilanx.biz/content/entidades/BancoLafiseS.A..png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 30 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.16%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡132,389.58\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la comisión\u003c/strong\u003e: 3.00%\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eComisión\u003c/strong\u003e: ₡600,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa fija\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.95%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 24\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa Libor 3 Meses + 8.00% o Piso de 8.25%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.66655%\u003c/td\u003e\u003ctd\u003eDel mes 25 hasta mes 360\u003c/td\u003e\u003c/tr\u003e                                                                                            \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 27/05/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: Sucursal de Pavas \u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario - tasa variable. - Scotiabank\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario - tasa variable.\u0022 src=\u0022https://bilanx.biz/content/entidades/ScotiabankdeCostaRicaS.A..png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario - tasa variable.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 25 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.06%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡131,933.88\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la comisión\u003c/strong\u003e: 1.00%\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eComisión\u003c/strong\u003e: ₡200,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 2.75%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.25%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 12\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 3.40%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.90%\u003c/td\u003e\u003ctd\u003eDel mes 13 hasta mes 36\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 4.75%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.25%\u003c/td\u003e\u003ctd\u003eDel mes 37 hasta mes 300\u003c/td\u003e\u003c/tr\u003e                                                                    \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 16/06/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: Expo Construcci\u0026#243;n.\u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario. - BAC San Jos\u0026#233;\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario.\u0022 src=\u0022https://bilanx.biz/content/entidades/BancoBACSanJos\u0026#233;S.A..png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 30 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.35%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡135,305.06\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa Libor 3 Meses + 6.50% o Piso de 7.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e7.16655%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 36\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa Libor 3 Meses + 7.90% o Piso de 8.50%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.56655%\u003c/td\u003e\u003ctd\u003eDel mes 37 hasta mes 360\u003c/td\u003e\u003c/tr\u003e                                                                                            \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 21/06/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: BAC San Jos\u0026#233;, - https://server.iad.liveperson.net/hc/49782067/?visitor=\u0026amp;msessionkey=\u0026amp;cmd=file\u0026amp;file=visitorWantsToChat\u0026amp;site=49782067\u0026amp;channel=web\u0026amp;d=1242\u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario - tasa fija escalonada. - Banca Kristal\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario - tasa fija escalonada.\u0022 src=\u0022https://bilanx.biz/content/entidades/BancaKristal.png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario - tasa fija escalonada.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 30 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.40%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡126,413.60\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la comisión\u003c/strong\u003e: 2.00%\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eComisión\u003c/strong\u003e: ₡400,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 3.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.50%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 12\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 4.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e7.50%\u003c/td\u003e\u003ctd\u003eDel mes 13 hasta mes 24\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 5.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.50%\u003c/td\u003e\u003ctd\u003eDel mes 25 hasta mes 360\u003c/td\u003e\u003c/tr\u003e                                                                    \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 24/05/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: Recopilaci\u0026#243;n de datos v\u0026#237;a correo electr\u0026#243;nico.\u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n    \u003c/div\u003e\r\n    \u003cul\u003e\r\n            \u003cli\u003eTasa b\u0026#225;sica pasiva al 28/06/2016: 5.3%\u003c/li\u003e\r\n            \u003cli\u003eTasa NY Prime al 28/06/2016: 3.5%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 1 Mes al 28/06/2016: 0.4508%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 3 Meses al 28/06/2016: 0.64185%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 6 Meses al 28/06/2016: 0.93115%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 12 Meses al 28/06/2016: 1.2525%\u003c/li\u003e\r\n    \u003c/ul\u003e\r\n    \u003chr /\u003e\r\n    \u003cp\u003e\r\n        Tambi\u0026#233;n, usted aceptó recibir ofertas de otras entidades.\r\n        Si una entidad decide ofertarle le estaremos enviando un correo para notificarle.\r\n    \u003c/p\u003e\r\n    \u003cp\u003eUsted puede aceptar o rechazar las ofertas recibidas de otras entidades que usted no escogió en esta solicitud.\u003c/p\u003e\r\n    \u003cp\u003ePuede dejar de recibir ofertas cancelando la solicitud desde el menú de Oferentes.\u003c/p\u003e\r\n\u003cdiv style=\u0022text-align:center\u0022\u003e\u003csmall\u003eEste correo ha sido generado automáticamente, por favor no responder.\u003c/small\u003e\u003c/div\u003e"
	}]`

**Comment by thinkingserious** [comment]
@Surfrat could you also provide the raw json that is in the image above?

**Comment by georgeemr** [comment]
This? (sorry, I barely understand english)

```
{	
	"subject": "Su solicitud de crédito",
	"personalizations": [{
		"to": [{
			"email": "jorge@vehiventa.com"
		}]
	}],
	"content": [{
		"type": "text/plain",
		"value": "\r\n\r\nHola Adri\u0026#225;n Navarro!\r\nSu solicitud de Compra de lote ha sido creada.\r\n    Monto: ₡20,000,000.00\r\n    \r\n    Antes de que un ejecutivo acepte su solicitud, usted tiene la oportunidad de poder cancelarla en cualquier momento desde el menú de solicitudes.\r\n    \r\n    Los productos que usted solicitó son los siguientes:\r\n    \r\n            \r\n                Cr\u0026#233;dito hipotecario. - Lafise\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 30 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.16%\r\n                    Cuota aproximada: ₡132,389.58\r\n                        Seguros: por definir\r\n                        Porcentaje de la comisión: 3.00%\r\n                        Comisión: ₡600,000.00\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa fija6.95%Del mes 1 hasta mes 24                        Tasa Libor 3 Meses + 8.00% o Piso de 8.25%8.66655%Del mes 25 hasta mes 360                                                                                            \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 27/05/2016\r\n                    Fuente: Sucursal de Pavas \r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n            \r\n                Cr\u0026#233;dito hipotecario - tasa variable. - Scotiabank\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario - tasa variable.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 25 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.06%\r\n                    Cuota aproximada: ₡131,933.88\r\n                        Seguros: por definir\r\n                        Porcentaje de la comisión: 1.00%\r\n                        Comisión: ₡200,000.00\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa NY Prime + 2.75%6.25%Del mes 1 hasta mes 12                        Tasa NY Prime + 3.40%6.90%Del mes 13 hasta mes 36                        Tasa NY Prime + 4.75%8.25%Del mes 37 hasta mes 300                                                                    \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 16/06/2016\r\n                    Fuente: Expo Construcci\u0026#243;n.\r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n            \r\n                Cr\u0026#233;dito hipotecario. - BAC San Jos\u0026#233;\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 30 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.35%\r\n                    Cuota aproximada: ₡135,305.06\r\n                        Seguros: por definir\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa Libor 3 Meses + 6.50% o Piso de 7.00%7.16655%Del mes 1 hasta mes 36                        Tasa Libor 3 Meses + 7.90% o Piso de 8.50%8.56655%Del mes 37 hasta mes 360                                                                                            \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 21/06/2016\r\n                    Fuente: BAC San Jos\u0026#233;, - https://server.iad.liveperson.net/hc/49782067/?visitor=\u0026amp;msessionkey=\u0026amp;cmd=file\u0026amp;file=visitorWantsToChat\u0026amp;site=49782067\u0026amp;channel=web\u0026amp;d=1242\r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n            \r\n                Cr\u0026#233;dito hipotecario - tasa fija escalonada. - Banca Kristal\r\n                    \r\n                    Producto: Cr\u0026#233;dito hipotecario - tasa fija escalonada.\r\n                    Moneda del producto: D\u0026#243;lares\r\n                    Monto solicitado: ₡20,000,000.00\r\n                    Desembolso: ₡20,000,000.00\r\n                    Plazo: 30 años\r\n                    Porcentaje de la prima: 0.00\r\n                    Prima estimada: ₡0.00\r\n                    Tasa promedio: 8.40%\r\n                    Cuota aproximada: ₡126,413.60\r\n                        Seguros: por definir\r\n                        Porcentaje de la comisión: 2.00%\r\n                        Comisión: ₡400,000.00\r\n                    Gastos legales: ₡1,410,000.00 (Pueden variar dependiendo de la figura)\r\n                    Tasas:\r\n                    \r\nTasa NY Prime + 3.00%6.50%Del mes 1 hasta mes 12                        Tasa NY Prime + 4.00%7.50%Del mes 13 hasta mes 24                        Tasa NY Prime + 5.00%8.50%Del mes 25 hasta mes 360                                                                    \r\n\r\n                    Estas condiciones se encuentran actualizadas al: 24/05/2016\r\n                    Fuente: Recopilaci\u0026#243;n de datos v\u0026#237;a correo electr\u0026#243;nico.\r\n\r\n                 * Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\r\n            \r\n    \r\n    \r\n            Tasa b\u0026#225;sica pasiva al 28/06/2016: 5.3%\r\n            Tasa NY Prime al 28/06/2016: 3.5%\r\n            Tasa Libor 1 Mes al 28/06/2016: 0.4508%\r\n            Tasa Libor 3 Meses al 28/06/2016: 0.64185%\r\n            Tasa Libor 6 Meses al 28/06/2016: 0.93115%\r\n            Tasa Libor 12 Meses al 28/06/2016: 1.2525%\r\n    \r\n    \r\n    \r\n        Tambi\u0026#233;n, usted aceptó recibir ofertas de otras entidades.\r\n        Si una entidad decide ofertarle le estaremos enviando un correo para notificarle.\r\n    \r\n    Usted puede aceptar o rechazar las ofertas recibidas de otras entidades que usted no escogió en esta solicitud.\r\n    Puede dejar de recibir ofertas cancelando la solicitud desde el menú de Oferentes.\r\nEste correo ha sido generado automáticamente, por favor no responder."
	}, {
		"type": "text/html",
		"value": "\r\n\r\n\u003ch3 style=\u0022color:#650B5F\u0022\u003eHola Adri\u0026#225;n Navarro!\u003c/h3\u003e\r\n\u003cp style=\u0022color:#650B5F\u0022\u003eSu solicitud de Compra de lote ha sido creada.\u003c/p\u003e\r\n    \u003cp\u003eMonto: ₡20,000,000.00\u003c/p\u003e\r\n    \u003chr /\u003e\r\n    \u003cp\u003eAntes de que un ejecutivo acepte su solicitud, usted tiene la oportunidad de poder cancelarla en cualquier momento desde el menú de solicitudes.\u003c/p\u003e\r\n    \u003cbr /\u003e\r\n    \u003cstrong\u003eLos productos que usted solicitó son los siguientes:\u003c/strong\u003e\r\n    \u003cdiv\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario. - Lafise\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario.\u0022 src=\u0022https://bilanx.biz/content/entidades/BancoLafiseS.A..png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 30 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.16%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡132,389.58\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la comisión\u003c/strong\u003e: 3.00%\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eComisión\u003c/strong\u003e: ₡600,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa fija\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.95%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 24\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa Libor 3 Meses + 8.00% o Piso de 8.25%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.66655%\u003c/td\u003e\u003ctd\u003eDel mes 25 hasta mes 360\u003c/td\u003e\u003c/tr\u003e                                                                                            \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 27/05/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: Sucursal de Pavas \u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario - tasa variable. - Scotiabank\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario - tasa variable.\u0022 src=\u0022https://bilanx.biz/content/entidades/ScotiabankdeCostaRicaS.A..png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario - tasa variable.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 25 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.06%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡131,933.88\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la comisión\u003c/strong\u003e: 1.00%\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eComisión\u003c/strong\u003e: ₡200,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 2.75%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.25%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 12\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 3.40%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.90%\u003c/td\u003e\u003ctd\u003eDel mes 13 hasta mes 36\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 4.75%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.25%\u003c/td\u003e\u003ctd\u003eDel mes 37 hasta mes 300\u003c/td\u003e\u003c/tr\u003e                                                                    \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 16/06/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: Expo Construcci\u0026#243;n.\u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario. - BAC San Jos\u0026#233;\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario.\u0022 src=\u0022https://bilanx.biz/content/entidades/BancoBACSanJos\u0026#233;S.A..png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 30 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.35%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡135,305.06\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa Libor 3 Meses + 6.50% o Piso de 7.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e7.16655%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 36\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa Libor 3 Meses + 7.90% o Piso de 8.50%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.56655%\u003c/td\u003e\u003ctd\u003eDel mes 37 hasta mes 360\u003c/td\u003e\u003c/tr\u003e                                                                                            \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 21/06/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: BAC San Jos\u0026#233;, - https://server.iad.liveperson.net/hc/49782067/?visitor=\u0026amp;msessionkey=\u0026amp;cmd=file\u0026amp;file=visitorWantsToChat\u0026amp;site=49782067\u0026amp;channel=web\u0026amp;d=1242\u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n            \u003cdiv style=\u0022border: 1px solid grey;padding: 10px;\u0022\u003e\r\n                Cr\u0026#233;dito hipotecario - tasa fija escalonada. - Banca Kristal\r\n                    \u003cimg class=\u0022logoBanco\u0022 style=\u0022max-width:150px\u0022 data-plugin-tooltip role=\u0022button\u0022 data-toggle=\u0022tooltip\u0022 data-placement=\u0022right\u0022 title=\u0022Cr\u0026#233;dito hipotecario - tasa fija escalonada.\u0022 src=\u0022https://bilanx.biz/content/entidades/BancaKristal.png\u0022 alt=\u0022LogoBanco\u0022 /\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eProducto\u003c/strong\u003e: Cr\u0026#233;dito hipotecario - tasa fija escalonada.\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMoneda del producto\u003c/strong\u003e: D\u0026#243;lares\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eMonto solicitado\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eDesembolso\u003c/strong\u003e: ₡20,000,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePlazo\u003c/strong\u003e: 30 años\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la prima\u003c/strong\u003e: 0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003ePrima estimada\u003c/strong\u003e: ₡0.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasa promedio\u003c/strong\u003e: 8.40%\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eCuota aproximada\u003c/strong\u003e: ₡126,413.60\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eSeguros\u003c/strong\u003e: por definir\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003ePorcentaje de la comisión\u003c/strong\u003e: 2.00%\u003c/div\u003e\r\n                        \u003cdiv\u003e\u003cstrong\u003eComisión\u003c/strong\u003e: ₡400,000.00\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eGastos legales\u003c/strong\u003e: ₡1,410,000.00 \u003cspan class=\u0022Bilanx-color-papapya\u0022\u003e(Pueden variar dependiendo de la figura)\u003c/span\u003e\u003c/div\u003e\r\n                    \u003cdiv\u003e\u003cstrong\u003eTasas\u003c/strong\u003e:\u003c/div\u003e\r\n                    \u003ctable class=\u0022table\u0022\u003e\r\n\u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 3.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e6.50%\u003c/td\u003e\u003ctd\u003eDel mes 1 hasta mes 12\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 4.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e7.50%\u003c/td\u003e\u003ctd\u003eDel mes 13 hasta mes 24\u003c/td\u003e\u003c/tr\u003e                        \u003ctr class=\u0022black\u0022\u003e\u003ctd\u003e\u003cstrong\u003eTasa NY Prime + 5.00%\u003c/strong\u003e\u003c/td\u003e\u003ctd\u003e8.50%\u003c/td\u003e\u003ctd\u003eDel mes 25 hasta mes 360\u003c/td\u003e\u003c/tr\u003e                                                                    \u003c/table\u003e\r\n\r\n                    \u003csmall\u003eEstas condiciones se encuentran actualizadas al: 24/05/2016\u003c/small\u003e\r\n                    \u003cbr /\u003e\u003csmall\u003eFuente: Recopilaci\u0026#243;n de datos v\u0026#237;a correo electr\u0026#243;nico.\u003c/small\u003e\r\n\r\n                \u003cbr /\u003e * \u003csmall\u003eLas tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.\u003c/small\u003e\r\n            \u003c/div\u003e\r\n    \u003c/div\u003e\r\n    \u003cul\u003e\r\n            \u003cli\u003eTasa b\u0026#225;sica pasiva al 28/06/2016: 5.3%\u003c/li\u003e\r\n            \u003cli\u003eTasa NY Prime al 28/06/2016: 3.5%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 1 Mes al 28/06/2016: 0.4508%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 3 Meses al 28/06/2016: 0.64185%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 6 Meses al 28/06/2016: 0.93115%\u003c/li\u003e\r\n            \u003cli\u003eTasa Libor 12 Meses al 28/06/2016: 1.2525%\u003c/li\u003e\r\n    \u003c/ul\u003e\r\n    \u003chr /\u003e\r\n    \u003cp\u003e\r\n        Tambi\u0026#233;n, usted aceptó recibir ofertas de otras entidades.\r\n        Si una entidad decide ofertarle le estaremos enviando un correo para notificarle.\r\n    \u003c/p\u003e\r\n    \u003cp\u003eUsted puede aceptar o rechazar las ofertas recibidas de otras entidades que usted no escogió en esta solicitud.\u003c/p\u003e\r\n    \u003cp\u003ePuede dejar de recibir ofertas cancelando la solicitud desde el menú de Oferentes.\u003c/p\u003e\r\n\u003cdiv style=\u0022text-align:center\u0022\u003e\u003csmall\u003eEste correo ha sido generado automáticamente, por favor no responder.\u003c/small\u003e\u003c/div\u003e"
	}]
}
```

The raw html is:

```



<h3 style="color:#650B5F">Hola Adri&#225;n Navarro!</h3>
<p style="color:#650B5F">Su solicitud de Compra de lote ha sido creada.</p>
    <p>Monto: ₡20,000,000.00</p>
    <hr />
    <p>Antes de que un ejecutivo acepte su solicitud, usted tiene la oportunidad de poder cancelarla en cualquier momento desde el menú de solicitudes.</p>
    <br />
    <strong>Los productos que usted solicitó son los siguientes:</strong>
    <div>
            <div style="border: 1px solid grey;padding: 10px;">
                Cr&#233;dito hipotecario. - Lafise
                    <img class="logoBanco" style="max-width:150px" data-plugin-tooltip role="button" data-toggle="tooltip" data-placement="right" title="Cr&#233;dito hipotecario." src="https://bilanx.biz/content/entidades/BancoLafiseS.A..png" alt="LogoBanco" />
                    <div><strong>Producto</strong>: Cr&#233;dito hipotecario.</div>
                    <div><strong>Moneda del producto</strong>: D&#243;lares</div>
                    <div><strong>Monto solicitado</strong>: ₡20,000,000.00</div>
                    <div><strong>Desembolso</strong>: ₡20,000,000.00</div>
                    <div><strong>Plazo</strong>: 30 años</div>
                    <div><strong>Porcentaje de la prima</strong>: 0.00</div>
                    <div><strong>Prima estimada</strong>: ₡0.00</div>
                    <div><strong>Tasa promedio</strong>: 8.16%</div>
                    <div><strong>Cuota aproximada</strong>: ₡132,389.58</div>
                        <div><strong>Seguros</strong>: por definir</div>
                        <div><strong>Porcentaje de la comisión</strong>: 3.00%</div>
                        <div><strong>Comisión</strong>: ₡600,000.00</div>
                    <div><strong>Gastos legales</strong>: ₡1,410,000.00 <span class="Bilanx-color-papapya">(Pueden variar dependiendo de la figura)</span></div>
                    <div><strong>Tasas</strong>:</div>
                    <table class="table">
<tr class="black"><td><strong>Tasa fija</strong></td><td>6.95%</td><td>Del mes 1 hasta mes 24</td></tr>                        <tr class="black"><td><strong>Tasa Libor 3 Meses + 8.00% o Piso de 8.25%</strong></td><td>8.66655%</td><td>Del mes 25 hasta mes 360</td></tr>                                                                                            </table>

                    <small>Estas condiciones se encuentran actualizadas al: 27/05/2016</small>
                    <br /><small>Fuente: Sucursal de Pavas </small>

                <br /> * <small>Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.</small>
            </div>
            <div style="border: 1px solid grey;padding: 10px;">
                Cr&#233;dito hipotecario - tasa variable. - Scotiabank
                    <img class="logoBanco" style="max-width:150px" data-plugin-tooltip role="button" data-toggle="tooltip" data-placement="right" title="Cr&#233;dito hipotecario - tasa variable." src="https://bilanx.biz/content/entidades/ScotiabankdeCostaRicaS.A..png" alt="LogoBanco" />
                    <div><strong>Producto</strong>: Cr&#233;dito hipotecario - tasa variable.</div>
                    <div><strong>Moneda del producto</strong>: D&#243;lares</div>
                    <div><strong>Monto solicitado</strong>: ₡20,000,000.00</div>
                    <div><strong>Desembolso</strong>: ₡20,000,000.00</div>
                    <div><strong>Plazo</strong>: 25 años</div>
                    <div><strong>Porcentaje de la prima</strong>: 0.00</div>
                    <div><strong>Prima estimada</strong>: ₡0.00</div>
                    <div><strong>Tasa promedio</strong>: 8.06%</div>
                    <div><strong>Cuota aproximada</strong>: ₡131,933.88</div>
                        <div><strong>Seguros</strong>: por definir</div>
                        <div><strong>Porcentaje de la comisión</strong>: 1.00%</div>
                        <div><strong>Comisión</strong>: ₡200,000.00</div>
                    <div><strong>Gastos legales</strong>: ₡1,410,000.00 <span class="Bilanx-color-papapya">(Pueden variar dependiendo de la figura)</span></div>
                    <div><strong>Tasas</strong>:</div>
                    <table class="table">
<tr class="black"><td><strong>Tasa NY Prime + 2.75%</strong></td><td>6.25%</td><td>Del mes 1 hasta mes 12</td></tr>                        <tr class="black"><td><strong>Tasa NY Prime + 3.40%</strong></td><td>6.90%</td><td>Del mes 13 hasta mes 36</td></tr>                        <tr class="black"><td><strong>Tasa NY Prime + 4.75%</strong></td><td>8.25%</td><td>Del mes 37 hasta mes 300</td></tr>                                                                    </table>

                    <small>Estas condiciones se encuentran actualizadas al: 16/06/2016</small>
                    <br /><small>Fuente: Expo Construcci&#243;n.</small>

                <br /> * <small>Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.</small>
            </div>
            <div style="border: 1px solid grey;padding: 10px;">
                Cr&#233;dito hipotecario. - BAC San Jos&#233;
                    <img class="logoBanco" style="max-width:150px" data-plugin-tooltip role="button" data-toggle="tooltip" data-placement="right" title="Cr&#233;dito hipotecario." src="https://bilanx.biz/content/entidades/BancoBACSanJos&#233;S.A..png" alt="LogoBanco" />
                    <div><strong>Producto</strong>: Cr&#233;dito hipotecario.</div>
                    <div><strong>Moneda del producto</strong>: D&#243;lares</div>
                    <div><strong>Monto solicitado</strong>: ₡20,000,000.00</div>
                    <div><strong>Desembolso</strong>: ₡20,000,000.00</div>
                    <div><strong>Plazo</strong>: 30 años</div>
                    <div><strong>Porcentaje de la prima</strong>: 0.00</div>
                    <div><strong>Prima estimada</strong>: ₡0.00</div>
                    <div><strong>Tasa promedio</strong>: 8.35%</div>
                    <div><strong>Cuota aproximada</strong>: ₡135,305.06</div>
                        <div><strong>Seguros</strong>: por definir</div>
                    <div><strong>Gastos legales</strong>: ₡1,410,000.00 <span class="Bilanx-color-papapya">(Pueden variar dependiendo de la figura)</span></div>
                    <div><strong>Tasas</strong>:</div>
                    <table class="table">
<tr class="black"><td><strong>Tasa Libor 3 Meses + 6.50% o Piso de 7.00%</strong></td><td>7.16655%</td><td>Del mes 1 hasta mes 36</td></tr>                        <tr class="black"><td><strong>Tasa Libor 3 Meses + 7.90% o Piso de 8.50%</strong></td><td>8.56655%</td><td>Del mes 37 hasta mes 360</td></tr>                                                                                            </table>

                    <small>Estas condiciones se encuentran actualizadas al: 21/06/2016</small>
                    <br /><small>Fuente: BAC San Jos&#233;, - https://server.iad.liveperson.net/hc/49782067/?visitor=&amp;msessionkey=&amp;cmd=file&amp;file=visitorWantsToChat&amp;site=49782067&amp;channel=web&amp;d=1242</small>

                <br /> * <small>Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.</small>
            </div>
            <div style="border: 1px solid grey;padding: 10px;">
                Cr&#233;dito hipotecario - tasa fija escalonada. - Banca Kristal
                    <img class="logoBanco" style="max-width:150px" data-plugin-tooltip role="button" data-toggle="tooltip" data-placement="right" title="Cr&#233;dito hipotecario - tasa fija escalonada." src="https://bilanx.biz/content/entidades/BancaKristal.png" alt="LogoBanco" />
                    <div><strong>Producto</strong>: Cr&#233;dito hipotecario - tasa fija escalonada.</div>
                    <div><strong>Moneda del producto</strong>: D&#243;lares</div>
                    <div><strong>Monto solicitado</strong>: ₡20,000,000.00</div>
                    <div><strong>Desembolso</strong>: ₡20,000,000.00</div>
                    <div><strong>Plazo</strong>: 30 años</div>
                    <div><strong>Porcentaje de la prima</strong>: 0.00</div>
                    <div><strong>Prima estimada</strong>: ₡0.00</div>
                    <div><strong>Tasa promedio</strong>: 8.40%</div>
                    <div><strong>Cuota aproximada</strong>: ₡126,413.60</div>
                        <div><strong>Seguros</strong>: por definir</div>
                        <div><strong>Porcentaje de la comisión</strong>: 2.00%</div>
                        <div><strong>Comisión</strong>: ₡400,000.00</div>
                    <div><strong>Gastos legales</strong>: ₡1,410,000.00 <span class="Bilanx-color-papapya">(Pueden variar dependiendo de la figura)</span></div>
                    <div><strong>Tasas</strong>:</div>
                    <table class="table">
<tr class="black"><td><strong>Tasa NY Prime + 3.00%</strong></td><td>6.50%</td><td>Del mes 1 hasta mes 12</td></tr>                        <tr class="black"><td><strong>Tasa NY Prime + 4.00%</strong></td><td>7.50%</td><td>Del mes 13 hasta mes 24</td></tr>                        <tr class="black"><td><strong>Tasa NY Prime + 5.00%</strong></td><td>8.50%</td><td>Del mes 25 hasta mes 360</td></tr>                                                                    </table>

                    <small>Estas condiciones se encuentran actualizadas al: 24/05/2016</small>
                    <br /><small>Fuente: Recopilaci&#243;n de datos v&#237;a correo electr&#243;nico.</small>

                <br /> * <small>Las tasas en este correo pueden presentar variaciones con el pasar del tiempo. Consulte a su ejecutivo para verificar la información.</small>
            </div>
    </div>
    <ul>
            <li>Tasa b&#225;sica pasiva al 28/06/2016: 5.3%</li>
            <li>Tasa NY Prime al 28/06/2016: 3.5%</li>
            <li>Tasa Libor 1 Mes al 28/06/2016: 0.4508%</li>
            <li>Tasa Libor 3 Meses al 28/06/2016: 0.64185%</li>
            <li>Tasa Libor 6 Meses al 28/06/2016: 0.93115%</li>
            <li>Tasa Libor 12 Meses al 28/06/2016: 1.2525%</li>
    </ul>
    <hr />
    <p>
        Tambi&#233;n, usted aceptó recibir ofertas de otras entidades.
        Si una entidad decide ofertarle le estaremos enviando un correo para notificarle.
    </p>
    <p>Usted puede aceptar o rechazar las ofertas recibidas de otras entidades que usted no escogió en esta solicitud.</p>
    <p>Puede dejar de recibir ofertas cancelando la solicitud desde el menú de Oferentes.</p>
<div style="text-align:center"><small>Este correo ha sido generado automáticamente, por favor no responder.</small></div>

```

**Comment by thinkingserious** [comment]
Perfect, thanks!

**Comment by Surfrat** [comment]
Good news...
All my tests pass and the emails are sent successfully with ' in the html.

I will test my web app tomorrow.

**Comment by georgeemr** [comment]
@thinkingserious Everything is ok for me too. Thanks

**Comment by thinkingserious** [comment]
Fixed: 
- https://github.com/sendgrid/sendgrid-csharp/releases/tag/v7.0.7
- https://www.nuget.org/packages/Sendgrid/7.0.7

Thanks to all on this thread for your continued patience!
